server:
  port: ":8000"
  api_key: "api_key"

db:
  host       : "127.0.0.1"
  port       : "5432"
  database   : "gin_gorm_boilerplate"
  username   : "sample_db_user"
  password   : "1234"
  sslmode    : "disable"
